---
- name: Installer Nginx sur les instances EC2
  hosts: web
  become: yes
  tasks:

    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer le service Nginx
      service:
        name: nginx
        state: started
        enabled: yes
